import { createContext, useContext, useState, useEffect } from 'react'

/* ─── Translations ───────────────────────────────────────────── */
const translations = {
  en: {
    /* ── Navbar ── */
    nav_features:    'Features',
    nav_how:         'How it works',
    nav_pricing:     'Pricing',
    nav_reviews:     'Reviews',
    nav_signin:      'Sign in',
    nav_getstarted:  'Get Started',
    nav_getstarted_free: 'Get Started Free',

    /* ── Hero ── */
    hero_badge:      'Now in Beta — Join 10,000+ food lovers',
    hero_title1:     'Smart Food Planning',
    hero_title2:     'Redefined',
    hero_sub:        'The all-in-one platform to discover recipes, plan your meals, and track nutrition — beautifully designed for food enthusiasts and health-conscious living.',
    hero_cta1:       'Start for Free',
    hero_cta2:       '▶ Watch Demo',
    hero_proof:      '10,000+ happy users worldwide',
    hero_card_title: 'Weekly Meal Plan',
    hero_card_active:'Active',
    hero_shopping:   '🛒 Shopping List',
    hero_of_daily:   'of 2,850 daily goal',
    days: ['Mon','Tue','Wed','Thu','Fri'],
    shop_items: ['Chicken breast','Olive oil','Fresh basil','Parmesan'],
    hero_recipe_name: 'Caesar Salad Supreme',
    hero_recipe_time: '25 min',
    hero_recipe_srv:  '2 servings',
    hero_recipe_diff: 'Easy',
    hero_macros: ['Protein','Carbs','Fat'],

    /* ── Features ── */
    features_label:  'Features',
    features_title:  'Everything you need to eat',
    features_title2: 'smarter',
    features_sub:    'A complete toolkit for recipe lovers, meal preppers, and anyone who wants to take control of their nutrition.',
    features: [
      { icon: '🍽️', title: 'Smart Recipe Management',  desc: 'Discover, save, and organize thousands of recipes with intelligent tagging, search, and filtering. Scale ingredients with one click.', tag: 'Core feature' },
      { icon: '📅', title: 'Intelligent Meal Planning',  desc: 'Plan your week visually with a drag-and-drop calendar. Get AI-powered suggestions based on your preferences and dietary goals.',      tag: 'Most loved' },
      { icon: '🛒', title: 'Auto Shopping Lists',        desc: 'Generate consolidated shopping lists from any meal plan. Automatically groups items by category and removes duplicates.',               tag: 'Time saver' },
      { icon: '📊', title: 'Nutritional Insights',       desc: 'Track macros, calories, and micronutrients in real time. Visualize your weekly nutrition balance with beautiful charts.',                 tag: 'Health focused' },
      { icon: '🤝', title: 'Community & Sharing',        desc: 'Share your favorite recipes with the community, follow top cooks, and collaborate on meal plans with family and friends.',               tag: 'Coming soon' },
      { icon: '🔄', title: 'Multi-device Sync',          desc: 'Access your recipes and meal plans seamlessly across all your devices. Real-time sync keeps everything up-to-date.',                      tag: 'Always in sync' },
    ],

    /* ── How it works ── */
    how_label:  'How it works',
    how_title1: 'Up and running in',
    how_title2: '3 simple steps',
    how_sub:    'From zero to perfectly planned meals in under 5 minutes. No complicated setup, no learning curve.',
    steps: [
      { number: '01', emoji: '🎯', title: 'Create your profile',       desc: 'Tell us your dietary preferences, allergies, and health goals. Set your daily calorie target and cuisine preferences in minutes.' },
      { number: '02', emoji: '🔍', title: 'Discover & save recipes',   desc: 'Browse thousands of curated recipes. Filter by cuisine, difficulty, prep time, or ingredients you already have at home.' },
      { number: '03', emoji: '🚀', title: 'Plan & shop with ease',     desc: 'Arrange your weekly meals visually, then generate a smart shopping list. Track nutrition automatically as you log each meal.' },
    ],

    /* ── Stats ── */
    stats: [
      { icon: '👨‍🍳', value: '12K+',  label: 'Active Chefs' },
      { icon: '🍳',   value: '50K+',  label: 'Recipes Saved' },
      { icon: '📅',   value: '200K+', label: 'Meals Planned' },
      { icon: '⭐',   value: '4.9',   label: 'Average Rating' },
    ],

    /* ── Pricing ── */
    pricing_label:  'Pricing',
    pricing_title1: 'Simple, transparent',
    pricing_title2: 'pricing',
    pricing_sub:    'Start free forever. Upgrade when you need more power. No hidden fees, cancel anytime.',
    pricing_popular:'Most Popular',
    pricing_per_mo: '/mo',
    plans: [
      { name: 'Free',  price: '0',  desc: 'Perfect for getting started.',                              cta: 'Get Started Free',  features: ['Up to 50 saved recipes','Basic meal planning (1 week)','Shopping list generator','Community access','Mobile app'] },
      { name: 'Pro',   price: '9',  desc: 'For serious food enthusiasts who want the full experience.', cta: 'Start 14-day Trial', features: ['Unlimited saved recipes','Advanced meal planning','Full nutritional tracking','AI-powered suggestions','Priority support','Allergen alerts','Export & print plans'] },
      { name: 'Team',  price: '19', desc: 'For families managing meals together.',                      cta: 'Contact Sales',      features: ['Everything in Pro','Up to 5 family members','Shared meal plans','Collaborative shopping','Dedicated onboarding','Priority support'] },
    ],

    /* ── Testimonials ── */
    test_label:  'Testimonials',
    test_title1: 'Loved by food',
    test_title2: 'enthusiasts',
    test_sub:    'Join thousands of happy users who transformed their relationship with food using EDA2DA.',
    testimonials: [
      { stars: 5, quote: 'EDA2DA completely changed how our family plans meals. The shopping list feature alone saves us 2 hours every week. Absolutely love the clean design.', name: 'Anna K.',    role: 'Home Chef & Nutritionist', initial: 'A' },
      { stars: 5, quote: 'As a fitness coach, I recommend EDA2DA to all my clients. The nutritional tracking is spot-on and the meal planning calendar is incredibly intuitive.',    name: 'Marcus T.', role: 'Fitness Coach',             initial: 'M' },
      { stars: 5, quote: "I've tried every meal planning app out there. EDA2DA is the only one that actually sticks. The design is gorgeous and it genuinely helps me eat better.", name: 'Sophie R.', role: 'Food Blogger',               initial: 'S' },
    ],

    /* ── CTA ── */
    cta_title1:  'Start eating smarter',
    cta_title2:  'today',
    cta_sub:     'Join over 10,000 food lovers who already transformed how they plan, cook, and enjoy meals. Free forever, upgrade anytime.',
    cta_btn1:    'Get Started Free',
    cta_btn2:    'Schedule a Demo',
    cta_note:    ['✓ No credit card required', '✓ Free plan forever', '✓ Cancel anytime'],

    /* ── Footer ── */
    footer_desc:  'The intelligent platform for recipe management, meal planning, and nutritional insights. Built for food lovers, by food lovers.',
    footer_copy:  '© 2026 EDA2DA. All rights reserved.',
    footer_cols: {
      Product:   ['Features','Pricing','Changelog','Roadmap'],
      Resources: ['Documentation','Blog','Community','Support'],
      Company:   ['About','Careers','Press','Contact'],
    },
    footer_legal: ['Privacy Policy','Terms of Service','Cookie Policy'],

    /* ── Auth ── */
    login_title:     'Welcome back',
    login_sub:       'Sign in to your account',
    login_username:  'Username',
    login_password:  'Password',
    login_btn:       'Sign in →',
    login_loading:   'Signing in…',
    login_noaccount: "Don't have an account?",
    login_create:    'Create one for free',

    register_title:   'Create your account',
    register_sub:     'Start planning smarter meals today',
    register_free:    '✨ Free forever',
    register_username:'Username',
    register_email:   'Email address',
    register_password:'Password',
    register_btn:     'Create Free Account →',
    register_loading: 'Creating account…',
    register_terms:   'By creating an account you agree to our',
    register_terms_a: 'Terms',
    register_terms_b: 'and',
    register_terms_c: 'Privacy Policy',
    register_hasaccount: 'Already have an account?',
    register_signin: 'Sign in',

    /* ── Recipe form ── */
    recipe_add_btn:   'Add Recipe',
    recipe_form_title:'New Recipe',
    recipe_form_step: 'Step',
    recipe_form_step1_name: 'Basic info',
    recipe_form_step2_name: 'Cooking instructions',
    recipe_form_step3_name: 'Photo',
    recipe_photo_title:  'Add a photo of your dish',
    recipe_photo_sub:    'Drag & drop a photo here, or click to browse',
    recipe_photo_browse: 'Choose file',
    recipe_photo_change: 'Change photo',
    recipe_photo_skip:   'Save without photo',
    recipe_form_next: 'Next',
    recipe_form_back: 'Back',
    recipe_form_save: 'Save Recipe',
    recipe_form_saving:'Saving…',
    recipe_form_tip:  'Write step-by-step instructions. Use numbers (1. 2. 3.) or paragraphs for each step.',
    recipe_field_title:   'Recipe name',
    recipe_field_title_ph:'e.g. Caesar Salad',
    recipe_field_desc:    'Short description',
    recipe_field_desc_ph: 'A few words about the dish…',
    recipe_field_time:    'Cook time',
    recipe_field_diff:    'Difficulty',
    recipe_field_ingredients:  'Ingredients',
    recipe_ing_name_ph:        'Ingredient name…',
    recipe_ing_qty_ph:         'Qty',
    recipe_ing_add:            '+ Add ingredient',
    recipe_field_instructions: 'How to cook (step by step)',
    recipe_field_instructions_ph: 'Step 1. Heat a pan over medium heat...\nStep 2. Add oil and garlic...\nStep 3. ...',
    recipe_instructions_label: 'Instructions',
    recipe_no_instructions: 'No instructions added yet.',
    diff_easy:   'Easy',
    diff_medium: 'Medium',
    diff_hard:   'Hard',

    /* ── Dashboard ── */
    dash_home:       'Dashboard',
    dash_recipes:    'Recipes',
    dash_mealplans:  'Meal Plans',
    dash_shopping:   'Shopping',
    dash_nutrition:  'Nutrition',
    dash_signout:    '← Sign out',
    dash_sub_home:       "Here's your food overview",
    dash_sub_recipes:    'Browse and search your recipes',
    dash_sub_mealplans:  'Manage your weekly meal plans',
    dash_sub_shopping:   'Shopping lists from your meal plans',
    dash_sub_nutrition:  'Nutritional breakdown of your meals',
    stat_recipes:    'Recipes available',
    stat_favorites:  'Favorites',
    stat_plans:      'Meal plans',
    stat_shopping:   'Shopping lists',
    stat_avg_cal:    'Avg. calories',
    stat_avg_per:    'Avg. calories per recipe',
    stat_protein:    'Avg. protein',
    stat_carbs:      'Avg. carbs',
    stat_fat:        'Avg. fat',
    sec_recent_recipes:  'Recent Recipes',
    sec_favorites:       'Favourite Recipes',
    sec_upcoming_plans:  'Upcoming Meal Plans',
    sec_recipes_count:   (n) => `${n} recipes`,
    sec_plans_count:     (n) => `${n} plan${n !== 1 ? 's' : ''}`,
    sec_macros:          'Average macros per recipe',
    sec_macros_sub:      (n) => `Based on ${n} recipes with nutritional data`,
    sec_top_cal:         'Top recipes by calories',
    btn_new_plan:    '+ New Plan',
    plan_create:         'Create plan',
    plan_week_of:        (d) => `Week of ${d}`,
    plan_no_plans:       'No meal plans yet',
    plan_no_plans_sub:   'Create your first weekly meal plan',
    plan_create_btn:     '+ Create week plan',
    plan_open:           'Open',
    plan_delete:         'Delete plan',
    plan_confirm_delete: 'Delete this meal plan?',
    plan_recipes_count:  (n) => `${n} recipes`,
    plan_slot_add:       'Add recipe',
    plan_picker_title:   'Add to plan',
    plan_picker_search:  'Search recipes…',
    plan_meal_breakfast: '🌅 Breakfast',
    plan_meal_lunch:     '🍽️ Lunch',
    plan_meal_dinner:    '🌙 Dinner',
    plan_total_cal:      'Total',
    plan_week_total:     'Week nutrition',
    plan_back:           '← Back to plans',
    plan_new_start:      'Start date',
    plan_new_end:        'End date',
    plan_new_save:       'Create plan',
    plan_new_cancel:     'Cancel',
    plan_kcal:           'kcal',
    filter_all:       'All',
    filter_soup:      '🍲 Soups',
    filter_main:      '🥩 Main dishes',
    filter_salad:     '🥗 Salads & bowls',
    filter_vegan:     '🌱 Vegan',
    filter_breakfast: '🍳 Breakfast',
    filter_dessert:   '🍫 Desserts',
    fav_add:          'Add to favorites',
    fav_remove:       'Remove from favorites',
    rating_your:      'Your rating',
    rating_avg:       (n, count) => `★ ${n} (${count})`,
    search_placeholder: 'Search recipes…',
    search_btn:      '🔍',
    empty_recipes:   'No recipes yet. Add some from the backend!',
    empty_favorites: 'No favourites yet. Heart ❤️ a recipe to add it here!',
    empty_plans:     'No meal plans yet. Create your first plan!',
    empty_shopping1: 'No meal plans yet — shopping lists are generated from your meal plans.',
    empty_shopping2: 'Shopping lists are empty. Add recipes to your meal plans first.',
    shop_no_plans:     'No meal plans yet',
    shop_no_plans_sub: 'Create a meal plan first, then your shopping list will appear here.',
    shop_empty:        'No ingredients found. Add recipes to your meal plan.',
    shop_all_plans:    'All plans',
    shop_progress:     (done, total) => `${done} of ${total} items bought`,
    shop_done:         'complete',
    shop_check_all:    'Check all',
    shop_uncheck_all:  'Uncheck all',
    shop_add_custom:   'Add',
    shop_add_custom_ph:'Add item…',
    mac_calories:    'Calories',
    mac_protein:     'Protein',
    mac_carbs:       'Carbohydrates',
    mac_fat:         'Fat',
    settings_theme:  'Theme',
    settings_lang:   'Language',
    theme_dark:      '🌙 Dark',
    theme_light:     '☀️ Light',
    lang_en:         '🇬🇧 EN',
    lang_ru:         '🇷🇺 RU',
    greeting:        (name) => `Hey, ${name} 👋`,

    /* ── Admin ── */
    dash_profile:        'Profile',
    dash_sub_profile:    'Your personal info and settings',
    profile_section_info:    'Personal info',
    profile_section_password:'Change password',
    profile_first_name:  'First name',
    profile_first_name_ph: 'John',
    profile_last_name:   'Last name',
    profile_last_name_ph:'Doe',
    profile_email:       'Email',
    profile_bio:         'About me',
    profile_bio_ph:      'A few words about yourself…',
    profile_save:        'Save changes',
    profile_saving:      'Saving…',
    profile_saved:       'Changes saved!',
    profile_save_err:    'Save error. Try again.',
    profile_pw_current:  'Current password',
    profile_pw_new:      'New password',
    profile_pw_confirm:  'Confirm new password',
    profile_pw_save:     'Change password',
    profile_pw_changed:  'Password changed!',
    profile_pw_mismatch: 'Passwords do not match.',
    profile_member_since:'Member since',
    profile_ratings:     'Ratings given',

    dash_admin:          'Admin Panel',
    dash_sub_admin:      'Moderate recipes and manage content',
    admin_tab_pending:   'Pending review',
    admin_tab_all:       'All recipes',
    admin_approve:       'Approve',
    admin_delete:        'Delete',
    admin_pending:       'Pending',
    admin_empty_pending: 'No recipes waiting for review 🎉',
    admin_confirm_delete:'Delete this recipe? This cannot be undone.',

    /* ── Subscription ── */
    sub_current_plan:   'Current Plan',
    sub_your_plan:      'Your plan',
    sub_upgrade:        'Upgrade plan',
    sub_downgrade:      'Change plan',
    sub_manage:         'Manage Subscription',
    sub_active:         'Active',
    sub_plan_free:      'Free',
    sub_plan_pro:       'Pro',
    sub_plan_family:    'Family',
    sub_badge_free:     '🆓 Free',
    sub_badge_pro:      '⚡ Pro',
    sub_badge_family:   '👨‍👩‍👧 Family',
    sub_switch_success: 'Plan changed successfully!',
    sub_switch_to:      (plan) => `Switch to ${plan}`,
    sub_current:        'Current plan',
    sub_popular:        'Most Popular',
  },

  ru: {
    /* ── Navbar ── */
    nav_features:    'Функции',
    nav_how:         'Как это работает',
    nav_pricing:     'Тарифы',
    nav_reviews:     'Отзывы',
    nav_signin:      'Войти',
    nav_getstarted:  'Начать',
    nav_getstarted_free: 'Начать бесплатно',

    /* ── Hero ── */
    hero_badge:      'Бета-версия — Уже 10 000+ любителей еды',
    hero_title1:     'Умное планирование питания',
    hero_title2:     'Переосмыслено',
    hero_sub:        'Единая платформа для поиска рецептов, планирования рациона и отслеживания нутриентов — создана для гурманов и тех, кто заботится о здоровье.',
    hero_cta1:       'Начать бесплатно',
    hero_cta2:       '▶ Смотреть демо',
    hero_proof:      '10 000+ счастливых пользователей',
    hero_card_title: 'План питания на неделю',
    hero_card_active:'Активен',
    hero_shopping:   '🛒 Список покупок',
    hero_of_daily:   'из 2 850 ккал в день',
    days: ['Пн','Вт','Ср','Чт','Пт'],
    shop_items: ['Куриная грудка','Оливковое масло','Свежий базилик','Пармезан'],
    hero_recipe_name: 'Цезарь делюкс',
    hero_recipe_time: '25 мин',
    hero_recipe_srv:  '2 порции',
    hero_recipe_diff: 'Лёгкий',
    hero_macros: ['Белки','Углев.','Жиры'],

    /* ── Features ── */
    features_label:  'Функции',
    features_title:  'Всё что нужно, чтобы питаться',
    features_title2: 'умнее',
    features_sub:    'Полный набор инструментов для любителей рецептов, тех, кто готовит заранее, и всех, кто хочет контролировать своё питание.',
    features: [
      { icon: '🍽️', title: 'Умное управление рецептами', desc: 'Открывайте, сохраняйте и организуйте тысячи рецептов с умными тегами, поиском и фильтрами. Масштабируйте ингредиенты одним кликом.', tag: 'Основная функция' },
      { icon: '📅', title: 'Интеллектуальное планирование', desc: 'Планируйте неделю визуально с перетаскиванием. Получайте AI-рекомендации на основе ваших предпочтений и целей.',      tag: 'Самое любимое' },
      { icon: '🛒', title: 'Авто-списки покупок',        desc: 'Создавайте сводные списки покупок из любого плана питания. Автоматически группирует продукты по категориям.',               tag: 'Экономия времени' },
      { icon: '📊', title: 'Нутриционная аналитика',       desc: 'Отслеживайте макросы, калории и микронутриенты в реальном времени. Визуализируйте баланс питания с помощью красивых графиков.', tag: 'Здоровый фокус' },
      { icon: '🤝', title: 'Сообщество и обмен',        desc: 'Делитесь любимыми рецептами, подписывайтесь на топ-поваров и создавайте совместные планы питания с семьёй.',               tag: 'Скоро' },
      { icon: '🔄', title: 'Синхронизация устройств',          desc: 'Получайте доступ к рецептам и планам питания на всех устройствах. Синхронизация в реальном времени.',                      tag: 'Всегда актуально' },
    ],

    /* ── How it works ── */
    how_label:  'Как это работает',
    how_title1: 'Готово',
    how_title2: 'за 3 простых шага',
    how_sub:    'От нуля до идеально спланированного питания менее чем за 5 минут. Без сложной настройки.',
    steps: [
      { number: '01', emoji: '🎯', title: 'Создайте профиль',       desc: 'Укажите пищевые предпочтения, аллергии и цели здоровья. Задайте целевую калорийность и предпочтения кухни за минуты.' },
      { number: '02', emoji: '🔍', title: 'Находите и сохраняйте рецепты',   desc: 'Просматривайте тысячи тщательно подобранных рецептов. Фильтруйте по кухне, сложности, времени приготовления.' },
      { number: '03', emoji: '🚀', title: 'Планируйте и покупайте легко',     desc: 'Расставляйте блюда визуально, затем создавайте умный список покупок. Нутриция отслеживается автоматически.' },
    ],

    /* ── Stats ── */
    stats: [
      { icon: '👨‍🍳', value: '12К+',  label: 'Активных поваров' },
      { icon: '🍳',   value: '50К+',  label: 'Рецептов сохранено' },
      { icon: '📅',   value: '200К+', label: 'Блюд запланировано' },
      { icon: '⭐',   value: '4.9',   label: 'Средний рейтинг' },
    ],

    /* ── Pricing ── */
    pricing_label:  'Тарифы',
    pricing_title1: 'Простые, прозрачные',
    pricing_title2: 'тарифы',
    pricing_sub:    'Начните бесплатно навсегда. Переходите на следующий уровень когда нужно. Без скрытых платежей.',
    pricing_popular:'Самый популярный',
    pricing_per_mo: '/мес',
    plans: [
      { name: 'Бесплатно', price: '0',  desc: 'Идеально для начала.',                                    cta: 'Начать бесплатно',   features: ['До 50 сохранённых рецептов','Базовое планирование (1 неделя)','Генератор списков покупок','Доступ к сообществу','Мобильное приложение'] },
      { name: 'Pro',        price: '9',  desc: 'Для серьёзных любителей еды, которым нужен весь функционал.', cta: 'Пробный период 14 дней', features: ['Неограниченно рецептов','Расширенное планирование','Полное отслеживание нутриентов','AI-рекомендации','Приоритетная поддержка','Предупреждения об аллергенах','Экспорт и печать планов'] },
      { name: 'Семейный',   price: '19', desc: 'Для семей, которые планируют питание вместе.',               cta: 'Связаться с продажами', features: ['Всё из Pro','До 5 членов семьи','Совместные планы питания','Коллаборативные покупки','Персональный онбординг','Приоритетная поддержка'] },
    ],

    /* ── Testimonials ── */
    test_label:  'Отзывы',
    test_title1: 'Любимый',
    test_title2: 'любителями еды',
    test_sub:    'Присоединяйтесь к тысячам пользователей, изменивших своё отношение к питанию с EDA2DA.',
    testimonials: [
      { stars: 5, quote: 'EDA2DA полностью изменил то, как наша семья планирует питание. Функция списка покупок экономит нам 2 часа каждую неделю. Обожаю чистый дизайн.', name: 'Анна К.',    role: 'Домашний шеф и нутрициолог', initial: 'А' },
      { stars: 5, quote: 'Как фитнес-тренер, я рекомендую EDA2DA всем своим клиентам. Отслеживание нутриентов точное, а календарь планирования питания невероятно интуитивный.',    name: 'Маркус Т.', role: 'Фитнес-тренер',             initial: 'М' },
      { stars: 5, quote: 'Я пробовал все приложения для планирования питания. EDA2DA — единственное, которое реально прижилось. Дизайн великолепен и реально помогает питаться лучше.', name: 'Соня Р.',   role: 'Фуд-блогер',               initial: 'С' },
    ],

    /* ── CTA ── */
    cta_title1:  'Начни питаться умнее',
    cta_title2:  'уже сегодня',
    cta_sub:     'Присоединяйтесь к 10 000+ любителям еды, которые уже изменили то, как планируют, готовят и наслаждаются блюдами. Бесплатно навсегда.',
    cta_btn1:    'Начать бесплатно',
    cta_btn2:    'Запланировать демо',
    cta_note:    ['✓ Без кредитной карты', '✓ Бесплатный тариф навсегда', '✓ Отмена в любое время'],

    /* ── Footer ── */
    footer_desc:  'Интеллектуальная платформа для управления рецептами, планирования питания и нутриционной аналитики. Создана любителями еды для любителей еды.',
    footer_copy:  '© 2026 EDA2DA. Все права защищены.',
    footer_cols: {
      Продукт:   ['Функции','Тарифы','Обновления','Дорожная карта'],
      Ресурсы:   ['Документация','Блог','Сообщество','Поддержка'],
      Компания:  ['О нас','Вакансии','Пресс-кит','Контакты'],
    },
    footer_legal: ['Политика конфиденциальности','Условия использования','Cookie-политика'],

    /* ── Recipe form ── */
    recipe_add_btn:   'Добавить рецепт',
    recipe_form_title:'Новый рецепт',
    recipe_form_step: 'Шаг',
    recipe_form_step1_name: 'Основная информация',
    recipe_form_step2_name: 'Способ приготовления',
    recipe_form_step3_name: 'Фото',
    recipe_photo_title:  'Добавьте фото готового блюда',
    recipe_photo_sub:    'Перетащите фото сюда или нажмите для выбора',
    recipe_photo_browse: 'Выбрать файл',
    recipe_photo_change: 'Изменить фото',
    recipe_photo_skip:   'Сохранить без фото',
    recipe_form_next: 'Далее',
    recipe_form_back: 'Назад',
    recipe_form_save: 'Сохранить рецепт',
    recipe_form_saving:'Сохранение…',
    recipe_form_tip:  'Опишите приготовление пошагово. Используйте нумерацию (1. 2. 3.) или абзацы для каждого шага.',
    recipe_field_title:   'Название рецепта',
    recipe_field_title_ph:'например: Паста Карбонара',
    recipe_field_desc:    'Краткое описание',
    recipe_field_desc_ph: 'Пару слов о блюде…',
    recipe_field_time:    'Время готовки',
    recipe_field_diff:    'Сложность',
    recipe_field_ingredients:  'Ингредиенты',
    recipe_ing_name_ph:        'Название ингредиента…',
    recipe_ing_qty_ph:         'Кол-во',
    recipe_ing_add:            '+ Добавить ингредиент',
    recipe_field_instructions: 'Способ приготовления (пошагово)',
    recipe_field_instructions_ph: 'Шаг 1. Разогрейте сковороду на среднем огне...\nШаг 2. Добавьте масло и чеснок...\nШаг 3. ...',
    recipe_instructions_label: 'Приготовление',
    recipe_no_instructions: 'Инструкции пока не добавлены.',
    diff_easy:   'Лёгкий',
    diff_medium: 'Средний',
    diff_hard:   'Сложный',

    /* ── Auth ── */
    login_title:     'Добро пожаловать',
    login_sub:       'Войдите в свой аккаунт',
    login_username:  'Имя пользователя',
    login_password:  'Пароль',
    login_btn:       'Войти →',
    login_loading:   'Вход…',
    login_noaccount: 'Нет аккаунта?',
    login_create:    'Создайте бесплатно',

    register_title:   'Создайте аккаунт',
    register_sub:     'Начните планировать питание умнее',
    register_free:    '✨ Бесплатно навсегда',
    register_username:'Имя пользователя',
    register_email:   'Адрес эл. почты',
    register_password:'Пароль',
    register_btn:     'Создать бесплатный аккаунт →',
    register_loading: 'Создание аккаунта…',
    register_terms:   'Создавая аккаунт, вы соглашаетесь с',
    register_terms_a: 'Условиями',
    register_terms_b: 'и',
    register_terms_c: 'Политикой конфиденциальности',
    register_hasaccount: 'Уже есть аккаунт?',
    register_signin: 'Войти',

    /* ── Dashboard ── */
    dash_home:       'Главная',
    dash_recipes:    'Рецепты',
    dash_mealplans:  'Планы питания',
    dash_shopping:   'Покупки',
    dash_nutrition:  'Нутриция',
    dash_signout:    '← Выйти',
    dash_sub_home:       'Обзор вашего питания',
    dash_sub_recipes:    'Просматривайте и ищите рецепты',
    dash_sub_mealplans:  'Управляйте планами питания',
    dash_sub_shopping:   'Списки покупок из планов питания',
    dash_sub_nutrition:  'Питательная ценность ваших блюд',
    stat_recipes:    'Рецептов',
    stat_favorites:  'Избранных',
    stat_plans:      'Планов питания',
    stat_shopping:   'Списков покупок',
    stat_avg_cal:    'Ср. калорийность',
    stat_avg_per:    'Ср. калорийность на рецепт',
    stat_protein:    'Ср. белки',
    stat_carbs:      'Ср. углеводы',
    stat_fat:        'Ср. жиры',
    sec_recent_recipes:  'Последние рецепты',
    sec_favorites:       'Избранные рецепты',
    sec_upcoming_plans:  'Ближайшие планы питания',
    sec_recipes_count:   (n) => `${n} рецептов`,
    sec_plans_count:     (n) => `${n} ${n === 1 ? 'план' : n < 5 ? 'плана' : 'планов'}`,
    sec_macros:          'Средние макросы на рецепт',
    sec_macros_sub:      (n) => `На основе ${n} рецептов с данными о питании`,
    sec_top_cal:         'Топ рецептов по калориям',
    btn_new_plan:    '+ Новый план',
    plan_create:         'Создать план',
    plan_week_of:        (d) => `Неделя с ${d}`,
    plan_no_plans:       'Планов питания пока нет',
    plan_no_plans_sub:   'Создайте свой первый недельный план питания',
    plan_create_btn:     '+ Создать план на неделю',
    plan_open:           'Открыть',
    plan_delete:         'Удалить план',
    plan_confirm_delete: 'Удалить этот план питания?',
    plan_recipes_count:  (n) => `${n} рецептов`,
    plan_slot_add:       'Добавить',
    plan_picker_title:   'Добавить в план',
    plan_picker_search:  'Поиск рецептов…',
    plan_meal_breakfast: '🌅 Завтрак',
    plan_meal_lunch:     '🍽️ Обед',
    plan_meal_dinner:    '🌙 Ужин',
    plan_total_cal:      'Итого',
    plan_week_total:     'Нутриция за неделю',
    plan_back:           '← К планам',
    plan_new_start:      'Дата начала',
    plan_new_end:        'Дата окончания',
    plan_new_save:       'Создать план',
    plan_new_cancel:     'Отмена',
    plan_kcal:           'ккал',
    filter_all:       'Все',
    filter_soup:      '🍲 Супы',
    filter_main:      '🥩 Вторые блюда',
    filter_salad:     '🥗 Салаты и боулы',
    filter_vegan:     '🌱 Веганское',
    filter_breakfast: '🍳 Завтраки',
    filter_dessert:   '🍫 Десерты',
    fav_add:          'В избранное',
    fav_remove:       'Убрать из избранного',
    rating_your:      'Ваша оценка',
    rating_avg:       (n, count) => `★ ${n} (${count})`,
    search_placeholder: 'Поиск рецептов…',
    search_btn:      '🔍',
    empty_recipes:   'Рецептов пока нет. Добавьте через бэкенд!',
    empty_favorites: 'Нет избранных. Нажмите ❤️ на рецепте, чтобы добавить сюда!',
    empty_plans:     'Планов питания пока нет. Создайте первый!',
    empty_shopping1: 'Нет планов питания — списки покупок формируются из них.',
    empty_shopping2: 'Списки покупок пусты. Сначала добавьте рецепты в план.',
    shop_no_plans:     'Планов питания пока нет',
    shop_no_plans_sub: 'Сначала создайте план питания — список покупок появится здесь.',
    shop_empty:        'Ингредиенты не найдены. Добавьте рецепты в план питания.',
    shop_all_plans:    'Все планы',
    shop_progress:     (done, total) => `Куплено ${done} из ${total}`,
    shop_done:         'выполнено',
    shop_check_all:    'Отметить все',
    shop_uncheck_all:  'Снять отметки',
    shop_add_custom:   'Добавить',
    shop_add_custom_ph:'Добавить позицию…',
    mac_calories:    'Калории',
    mac_protein:     'Белки',
    mac_carbs:       'Углеводы',
    mac_fat:         'Жиры',
    settings_theme:  'Тема',
    settings_lang:   'Язык',
    theme_dark:      '🌙 Тёмная',
    theme_light:     '☀️ Светлая',
    lang_en:         '🇬🇧 EN',
    lang_ru:         '🇷🇺 RU',
    greeting:        (name) => `Привет, ${name} 👋`,

    /* ── Admin ── */
    dash_profile:        'Профиль',
    dash_sub_profile:    'Личные данные и настройки',
    profile_section_info:    'Личные данные',
    profile_section_password:'Смена пароля',
    profile_first_name:  'Имя',
    profile_first_name_ph: 'Иван',
    profile_last_name:   'Фамилия',
    profile_last_name_ph:'Иванов',
    profile_email:       'Email',
    profile_bio:         'О себе',
    profile_bio_ph:      'Пару слов о себе…',
    profile_save:        'Сохранить изменения',
    profile_saving:      'Сохранение…',
    profile_saved:       'Изменения сохранены!',
    profile_save_err:    'Ошибка сохранения. Попробуйте снова.',
    profile_pw_current:  'Текущий пароль',
    profile_pw_new:      'Новый пароль',
    profile_pw_confirm:  'Подтвердите новый пароль',
    profile_pw_save:     'Изменить пароль',
    profile_pw_changed:  'Пароль успешно изменён!',
    profile_pw_mismatch: 'Пароли не совпадают.',
    profile_member_since:'На сайте с',
    profile_ratings:     'Оценок выдано',

    dash_admin:          'Панель админа',
    dash_sub_admin:      'Модерация рецептов и управление контентом',
    admin_tab_pending:   'На проверке',
    admin_tab_all:       'Все рецепты',
    admin_approve:       'Одобрить',
    admin_delete:        'Удалить',
    admin_pending:       'На проверке',
    admin_empty_pending: 'Нет рецептов на проверке 🎉',
    admin_confirm_delete:'Удалить этот рецепт? Действие нельзя отменить.',

    /* ── Subscription ── */
    sub_current_plan:   'Текущий тариф',
    sub_your_plan:      'Ваш тариф',
    sub_upgrade:        'Сменить тариф',
    sub_downgrade:      'Сменить тариф',
    sub_manage:         'Управление подпиской',
    sub_active:         'Активен',
    sub_plan_free:      'Бесплатно',
    sub_plan_pro:       'Pro',
    sub_plan_family:    'Семейный',
    sub_badge_free:     '🆓 Бесплатно',
    sub_badge_pro:      '⚡ Pro',
    sub_badge_family:   '👨‍👩‍👧 Семейный',
    sub_switch_success: 'Тариф успешно изменён!',
    sub_switch_to:      (plan) => `Перейти на ${plan}`,
    sub_current:        'Текущий тариф',
    sub_popular:        'Популярный',
  },
}

/* ─── Theme tokens ───────────────────────────────────────────── */
export const themes = {
  dark: {
    bg:              '#0A1428',
    bgCard:          'rgba(255,255,255,.04)',
    bgCardHover:     'rgba(255,255,255,.07)',
    border:          'rgba(255,255,255,.07)',
    borderBright:    'rgba(255,255,255,.14)',
    text:            '#FFFFFF',
    textSec:         '#94A3B8',
    textMuted:       '#506280',
    sidebar:         'rgba(255,255,255,.03)',
    sidebarBorder:   'rgba(255,255,255,.07)',
    navActive:       'rgba(0,240,255,.08)',
    navActiveBorder: 'rgba(0,240,255,.15)',
    navActiveText:   '#FFFFFF',
    navText:         '#94A3B8',
    input:           'rgba(255,255,255,.04)',
    inputBorder:     'rgba(255,255,255,.10)',
    inputText:       '#FFFFFF',
    shadow:          '0 24px 64px rgba(0,0,0,.5)',
    cardBorder:      'rgba(255,255,255,.08)',
    statGrad:        'linear-gradient(135deg,#00F0FF,#7B5EFF)',
    blob1:           'radial-gradient(circle, rgba(0,240,255,.1) 0%, transparent 70%)',
    blob2:           'radial-gradient(circle, rgba(123,94,255,.12) 0%, transparent 70%)',
    gridDot:         'rgba(255,255,255,.05)',
    logoutColor:     '#506280',
    logoutBorder:    'rgba(255,255,255,.08)',
    emptyBorder:     'rgba(255,255,255,.08)',
    shopBg:          'rgba(255,255,255,.03)',
    shopBorder:      'rgba(255,255,255,.06)',
    barBg:           'rgba(255,255,255,.06)',
  },
  light: {
    bg:              '#EEF2F8',
    bgCard:          'rgba(255,255,255,.88)',
    bgCardHover:     'rgba(255,255,255,.98)',
    border:          'rgba(0,0,0,.07)',
    borderBright:    'rgba(0,0,0,.14)',
    text:            '#0F172A',
    textSec:         '#64748B',
    textMuted:       '#94A3B8',
    sidebar:         'rgba(255,255,255,.75)',
    sidebarBorder:   'rgba(0,0,0,.07)',
    navActive:       'rgba(0,186,210,.1)',
    navActiveBorder: 'rgba(0,186,210,.3)',
    navActiveText:   '#0A1428',
    navText:         '#64748B',
    input:           'rgba(0,0,0,.03)',
    inputBorder:     'rgba(0,0,0,.12)',
    inputText:       '#0F172A',
    shadow:          '0 24px 64px rgba(0,0,0,.10)',
    cardBorder:      'rgba(0,0,0,.07)',
    statGrad:        'linear-gradient(135deg,#0099AA,#6B4FFF)',
    blob1:           'radial-gradient(circle, rgba(0,200,230,.18) 0%, transparent 70%)',
    blob2:           'radial-gradient(circle, rgba(123,94,255,.12) 0%, transparent 70%)',
    gridDot:         'rgba(0,0,0,.04)',
    logoutColor:     '#94A3B8',
    logoutBorder:    'rgba(0,0,0,.1)',
    emptyBorder:     'rgba(0,0,0,.1)',
    shopBg:          'rgba(0,0,0,.02)',
    shopBorder:      'rgba(0,0,0,.06)',
    barBg:           'rgba(0,0,0,.06)',
  },
}

/* ─── Context ────────────────────────────────────────────────── */
const AppContext = createContext(null)

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('eda2da_theme') || 'dark')
  const [lang,  setLang]  = useState(() => localStorage.getItem('eda2da_lang')  || 'en')

  const toggleTheme = () => setTheme(t => t === 'dark' ? 'light' : 'dark')
  const toggleLang  = () => setLang(l  => l  === 'en'   ? 'ru'   : 'en')

  useEffect(() => {
    localStorage.setItem('eda2da_theme', theme)
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  useEffect(() => {
    localStorage.setItem('eda2da_lang', lang)
    document.documentElement.setAttribute('lang', lang)
  }, [lang])

  const t = (key, ...args) => {
    const val = translations[lang][key]
    if (typeof val === 'function') return val(...args)
    return val ?? key
  }

  const thm = themes[theme]

  return (
    <AppContext.Provider value={{ theme, toggleTheme, lang, toggleLang, t, thm }}>
      {children}
    </AppContext.Provider>
  )
}

export const useApp = () => useContext(AppContext)
