# Generated by Django 5.0.4 on 2026-05-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_is_allergen_recipe_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_moderated',
            field=models.BooleanField(default=True),
        ),
    ]
