# Generated by Django 5.0.4 on 2026-05-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
